#pragma once
// This file is automatically generated.

namespace Hlsl
{
	extern const std::array<CStringA, 1> includes;
	namespace Render
	{
		extern const CStringA SimpleSolidPS;
		extern const CStringA SimpleSolidVS;
	}

	namespace StaticShaders
	{
		extern const std::array<uint8_t, 12540> FullScreenTriangleVS;
	}
}